### PR TITLE
VM/Client: fix HF switching. Fix TangerineWhistle update bug.

### LINKED ISSUE #1090: Client -> Rinkeby: Consensus Error on Block 14182 (invalid receiptTrie)
At least we made it up to block 14182 after the fixes from #1089 - that's something. To relativize a bit, there were only 10 or so transactions along the way. 😂  😂  😂

This one is significantly more complex, here is the output:

image

image

Block on Rinkeby: [14182](https://rinkeby.etherscan.io/block/14182)

Some first observations and thoughts:

- Shouldn't be related to #1076, since this one here is on `SpuriousDragon` and #1076 is fixing a pre-Homestead bug (that said, @jochem-brouwer you mentioned that you need to fix other bugs. Have these already been fixed and are these independent from the Homestead HF and might play a role here?)
- I have to say that this early breaking on PoA puzzles me since mainnet was running so smoothly for such a long period of blocks: this might be an indicator that this has something to do with the PoA implementation as well, can't think of anything atm though
- Gas used matches (with `1339314`), being an indicator that there is likely nothing wrong along opcode execution I guess? 🤔

Ok. We'll see. 😄  😋

### PR DESCRIPTION
**Pull request by jochem-brouwer**
Closes #1090. Cherry-picked from #1094.

Very nasty bug. There are two problems:

(1) Client does not update the opcodes of VM when we change hard forks. In practice, some stuff happens though: if we update a context variable which we were already using (like tx data gas cost for nonzero data) then this is used (as we dynamically fetch this from the current Common). However, if a HF introduces new opcodes, then these are not added to VM and are thus not accessible. 

(2) We never updated TangerineWhistle gas cost changes in the first place. If you instantiate a Common with Chainstart, then switch to TangerineWhistle, and even called `_updateOpcodes()` before, then gas costs are *not* updated in the VM.

(Side note: also weird that tests did not cover this. On the other hand, there are not that many tests where we check HF switching).

### CODE REVIEW

File: packages/client/lib/sync/execution/vmexecution.ts [hunk 1]
```diff
@@ -49,6 +49,7 @@ export class VMExecution extends Execution {
     const blockNumber = headBlock.header.number.toNumber()
     this.config.execCommon.setHardforkByBlockNumber(blockNumber)
     this.hardfork = this.config.execCommon.hardfork()
+    this.vm._updateOpcodes()
```
Comment (jochem-brouwer) [inline packages/client/lib/sync/execution/vmexecution.ts:52]: Side note: we can also launch VM with the `selectHardforkByBlockNumber: true` option, then this stuff is handled in the VM. We would only not directly see in Client that we are switching HFs. This would generally go well if we always start the Common with Chainstart, and then let VM check per block number (via this option) if we should change it.

**Comment by jochem-brouwer** [comment]
Also please check that Client now processes the wrong rinkeby block the right way. It does for me.

If client refuses to run the 14182 block, and you have already executed block 14181 previously, then you can temporarily change `client/lib/sync/execution/vmexecution.ts`, add this to `open()`:

```typescript
  async open(): Promise<void> {
    await this.vm.blockchain.setIteratorHead('vm', Buffer.from('b477241819c2222fe45f63300cc2b55760e08f626461f7d37deddcfcc6055def','hex'))
    const headBlock = await this.vm.blockchain.getIteratorHead()
    const blockNumber = headBlock.header.number.toNumber()
    this.config.execCommon.setHardforkByBlockNumber(blockNumber)
    this.hardfork = this.config.execCommon.hardfork()
    this.vm._updateOpcodes()
    this.config.logger.info(`Initializing VM execution hardfork=${this.hardfork}`)
  }
  ```
  
  This b477... hex is the hash of block 14181.

File: packages/client/lib/sync/execution/vmexecution.ts (hunk 1 above)
Comment (holgerd77) [reply packages/client/lib/sync/execution/vmexecution.ts:52]: Great find: already thought some time ago: would it make sense for such uses cases to make the `Common` also a class inheriting from `EventEmitter` and then submit an event `hardforkChanged` whenever a HF change has been triggered?

Then the VM can listen to this internally and itself do a call to `_updateOpcodes()`. Calling this from the outside is not so optimal and likely other users will stumble upon this as well.

(making a class an EventEmitter should be a non-breaking change I would say?)

Comment (jochem-brouwer) [reply packages/client/lib/sync/execution/vmexecution.ts:52]: Yeah, this would make a lot of sense. I think at the moment our packages are mostly built around non-changing Common hardforks. We also have this issue for instance: #969. Although I'm not sure if reacting on events would solve that particular problem in an elegant way 🤔 .

Comment (jochem-brouwer) [reply packages/client/lib/sync/execution/vmexecution.ts:52]: And it would indeed be non-breaking, since you only add methods. (Unless I'm missing some very specific things which might be broken if you suddenly start extending classes).

**Review by holgerd77 — APPROVED** [review]
Will give this an approval independently from this EventEmitter question, we can discuss separately and eventually update here along a subsequent PR.

**Comment by jochem-brouwer** [comment]
@holgerd77 can you check that Rinkeby block now processes on your node?

**Comment by holgerd77** [comment]
Synced from scratch and can confirm that the sync is going on. 🎉 🎉 🎉
