### PR TITLE
Blockchain: Clique-recently-signed False Positive Fix

### LINKED ISSUE #1930: Client: Release-blocking Client Bug
We have a too severe bug in the client to continue with the releases.

So basically: if a chain has a partially synced state (or is just synced from the beginning) and then the client is re-started we repeatedly get the following error:

grafik

(here is the initial sync for comparison, going well:)

grafik

I can confirm this for at least Rinkeby and Sepolia, for Mainnet things seem to work (so maybe this is a PoA related thing?).

This bug is *urgent* since it is actively blocking the current release round.

### PR DESCRIPTION
**Pull request by holgerd77**
Fixes #1930 

Triggered in the client in a reorg-like scenario on syncing a Clique consensus-based chain (Sepolia, Rinkeby,...)

### CODE REVIEW

**Review by g11tech — APPROVED** [review]

File: packages/blockchain/src/index.ts [hunk 1]
```diff
@@ -478,6 +478,9 @@ export default class Blockchain implements BlockchainInterface {
     // construct recent block signers list with this block
     let signers = this._cliqueLatestBlockSigners
     signers = signers.slice(signers.length < limit ? 0 : 1)
+    if (signers.length > 0 && !signers[signers.length - 1][0].eq(header.number.subn(1))) {
+      signers = []
```
Comment (ryanio) [inline packages/blockchain/src/index.ts:482]: Should we just return false here? With an explanatory comment like `// if the last signed block is not one from the current head we do not have a complete picture of the state to verify if too recently signed`

Comment (holgerd77) [reply packages/blockchain/src/index.ts]: Yes, guess that's the same, right?

Comment (holgerd77) [reply packages/blockchain/src/index.ts]: (but definitely better)

Comment (holgerd77) [reply packages/blockchain/src/index.ts]: Can you reapprove here?

**Review by ryanio — APPROVED** [review]
lgtm!
