### PR TITLE
Fix default value for empty access lists

### LINKED ISSUE #1178: Tx: AccessListEIP23930Transaction initialization not working with default AL value
Instantiation of AL txs is not working when no accessList value is provided, following error:

image

Fix is I guess to replace `emptyBuffer` with the empty list, this fix should be added to the #1174 releases.

### PR DESCRIPTION
**Pull request by jochem-brouwer**
Closes #1178

### CODE REVIEW

File: packages/tx/src/eip2930Transaction.ts [hunk 1]
```diff
@@ -137,7 +138,11 @@ export default class AccessListEIP2930Transaction extends BaseTransaction<Access
    * varying data types.
    */
   public constructor(txData: AccessListEIP2930TxData, opts: TxOptions = {}) {
-    const { chainId, accessList } = txData
+    // Have to split up the const/let part to make eslint happy
+    const { chainId } = txData
+    let { accessList } = txData
+
+    accessList = accessList ?? emptyAccessList
```
Comment (holgerd77) [inline packages/tx/src/eip2930Transaction.ts:145]: This is not necessary since in all cases default values are handled in the code below.

File: packages/tx/test/eip2930.spec.ts [hunk 2]
```diff
@@ -318,4 +318,14 @@ tape('[AccessListEIP2930Transaction]', function (t) {
...
+
+  t.test('should create and sign transactions without passing access list value', (st) => {
+    const tx = AccessListEIP2930Transaction.fromTxData({}, { common })
+    const signed = tx.sign(pKey)
+
+    st.deepEqual(tx.accessList, [])
+    st.deepEqual(signed.accessList, [])
+
+    st.end()
+  })
```
Comment (holgerd77) [inline packages/tx/test/eip2930.spec.ts:330]: Cool, thanks for an additional test on this! 😄

**Review by holgerd77 — APPROVED** [review]
LGTM

File: packages/tx/src/eip2930Transaction.ts (hunk 1 above)
Comment (jochem-brouwer) [reply packages/tx/src/eip2930Transaction.ts]: Yep.

**Comment by jochem-brouwer** [comment]
Ok, thanks for directly pushing 😄
