### PR TITLE
trie: improve node typings and class architecture 

### LINKED ISSUE #3704: Review and improve trie node typing
Currently, the trie `Node` base type is extended in the extension and leaf node implementations (but unexpectedly, not in the branch node implementation) and it has some typing issues, such as the `value()` function on different node classes being typed to return a `Uint8Array` but it can also return `null` or `Uint8Array[]`. This issue, and other similar typing issues or class design issues should be considered and fixed if possible or notes/documented for future review. Also see [this comment](https://github.com/ethereumjs/ethereumjs-monorepo/pull/3692#issuecomment-2374783456) for more context on the problem.

### PR DESCRIPTION
**Pull request by gabrocheleau**
This PR resolves #3704 by:
- Renaming the Node class to the more accurate `ExtensionAndLeafNodeBase` class and making it abstract.
- Removing the `encodeKey` method from the extension and leaf node classes as they were not used
- Adding RawExtensionNode and RawLeafNode types
- Removing the EmbeddedNode type and replacing it with the `NodeReferenceOrRawNode` type
- Adding a `BranchNodeBranchValue` type that fits the types of the values of the _branches of the branch node class.

### CODE REVIEW

File: packages/trie/src/node/extensionOrLeafNodeBase.ts [hunk 1]
```diff
@@ -3,23 +3,27 @@ import { RLP } from '@ethereumjs/rlp'
...
 
-import type { Nibbles } from '../types.js'
+import type { Nibbles, RawExtensionNode, RawLeafNode } from '../types.js'
 
-export class Node {
+export abstract class ExtensionOrLeafNodeBase {
   _nibbles: Nibbles
   _value: Uint8Array
-  _terminator: boolean
+  _isLeaf: boolean
```
Comment (jochem-brouwer) [inline packages/trie/src/node/extensionOrLeafNodeBase.ts:11]: With these changes I suggest we remove the `ExtensionNode` and `LeafNode` completely. We could introduce static constructors here which return the right node type. (`_isLeaf` thus needs to be public in order to determine if it is a leaf/extension node)

Comment (gabrocheleau) [reply packages/trie/src/node/extensionOrLeafNodeBase.ts:11]: I went back and forth on this earlier today, but figured it was better to have these classes separate just for naming and clarity purposes, just so that we can at least do `new LeafNode` and `new ExtensionNode` instead of something like `new ExtensionOrLeafNode(isLeaf: true)`. What do feel is the value in having them both be the same class?

Comment (jochem-brouwer) [reply packages/trie/src/node/extensionOrLeafNodeBase.ts:11]: You are right, the classes are much more clear for readability! Let's not change it.

**Review by acolytec3 — DISMISSED** [review]
This looks great.  Makes so much more sense now.

File: packages/trie/src/types.ts [hunk 2]
```diff
@@ -8,9 +8,17 @@ export type TrieNode = BranchNode | ExtensionNode | LeafNode
 
 export type Nibbles = number[]
 
+// [ encodedPath, key ]
```
Comment (jochem-brouwer) [inline packages/trie/src/types.ts:11]: Hmm, I find this documentation somewhat misleading. The `key` in this context would be the pointer to whatever hash this `ExtensionNode` points to. I think this is implied to by "key" but this might be confused with the MPT-keys (so the ones you use as `get` argument). Not sure what a better term here would be though. `referencedHash`? Or maybe `pointerHash`?

Comment (gabrocheleau) [reply packages/trie/src/types.ts:11]: I've copied what is in the ethereum.org documentation. I agree that it is not immediately obvious what this represents. I will remove these two comments and instead add a link to the docs.

Comment (acolytec3) [reply packages/trie/src/types.ts]: I dunno if I like the updated comment any better. The docs do explain what the extension node is, in that the `key` is the DB key for the next node. 

Can we get rid of the "raw node" terminology and just have extension nodes, which are simply the encoded path to the node and then the DB key for the next lookup, and then lead nodes, which are the encoded path and then the leaf value (which is either an rlp encoded account or null, right)?

Comment (gabrocheleau) [reply packages/trie/src/types.ts]: Yeah that's fair. 

I'm not sure I get the idea behind getting rid of the "raw node" terminology. We could do a renaming, but then we would have to rework the classes since these are already called "ExensionNode" and "LeafNode". Additionally, in comments and various places (e.g. methods like `decodeRawNode`), we have been referring to "raw nodes" quite often, and I would tend not to make changes that are too intrusive. 

I've updated the comment, let me know if that seems clear enough

**Review by acolytec3 — APPROVED** [review]
LGTM

**Review by jochem-brouwer — APPROVED** [review]
LGTM

File: packages/trie/src/types.ts [hunk 3]
```diff
@@ -8,9 +8,18 @@ export type TrieNode = BranchNode | ExtensionNode | LeafNode
 
 export type Nibbles = number[]
 
+// A raw node refers to the non-serialized, array form of the node
+// A raw extension node is a 2-item node, where the first item is the encoded path to the next node, and the second item is the reference to the next node
+// A raw leaf node is a 2-item node, where the first item is the remaining path to the leaf node, and the second item is the value
+// To learn more: https://ethereum.org/en/developers/docs/data-structures-and-encoding/patricia-merkle-trie/#optimization
```
Comment (jochem-brouwer) [inline packages/trie/src/types.ts:14]: Yes, great that the extra docs on top have been added. In the future this external URL could 404, so in general we should add extra comments if we point to external URLs :smile: :+1:
