### PR TITLE
util: bigint bytes fixes

### LINKED ISSUE #3180: Improve BigInt<>Bytes conversion helpers test coverage & address edge case issues
Our BigInt<>Bytes conversion helpers have been updated in the past few weeks, notably because of verkle work that required us to handle little endianness conversion. We have also encountered issues related to those helpers that could have been easily avoided if we had been testing those helpers more thoroughly.

There are also outstanding questions regarding those helpers (taken from #3169 ):

- Should bigIntToBytes on BigInt(0) return the empty array? (Note: this is super breaking so we cannot do it, we could introduce a new method?)
- Should setLengthLeft throw if the expected length is lower than the current length? (It is unknown if we should trim left or right 🤔 )

### LINKED ISSUE #4202: Mutation bug in `bytesToBigInt`
Usage of reverse on the bytes mutates the input:

```
export const bytesToBigInt = (bytes: Uint8Array, littleEndian = false): bigint => {
  if (littleEndian) {
    bytes.reverse()
  }
```
Will address in a follow up PR

### PR DESCRIPTION
**Pull request by gabrocheleau**
This PR:
- fixes #3180 
- fixes #4202 

Summary of the decisions and rationale (relevant with regards to our previous discussion on #3180 @jochem-brouwer )

- `bigIntToBytes(0n)`
  - Keep returning `[0]`.
  - Use `bigIntToUnpaddedBytes` when an empty array is desired.
  - `[0]` = “the number zero”, `[]` = “empty/absence”; semantically distinct and encoded differently in RLP.

- `setLengthLeft` truncation behavior
  - Default: throw if truncation would occur.
  - Add an explicit `allowTruncate` option to opt into truncation.
  - A padding helper should not silently lose data; callers must explicitly choose left vs right truncation.

- `bytesToBigInt([])`
  - Keep returning `0n`.
  - Treat empty bytes as zero and preserve roundtrips with `bigIntToUnpaddedBytes`.

- Runtime type checks
  - Add an `assertIsBytes()` helper (checking `instanceof Uint8Array`) and use it in `bytesToBigInt` and other bytes-accepting functions.
- Mutation bug in `bytesToBigInt`
  - Fix by using `.slice().reverse()` instead of `.reverse()` directly on the input.

### CODE REVIEW

File: packages/util/src/bytes.ts [hunk 1]
```diff
@@ -122,48 +123,72 @@ export const bigIntToBytes = (num: bigint, littleEndian = false): Uint8Array =>
...
     }
-    return msg.subarray(-length)
+    return right ? msg.subarray(0, length) : msg.subarray(-length)
   }
+  if (msg.length < length) {
+    return right
+      ? new Uint8Array([...msg, ...new Uint8Array(length - msg.length)])
+      : new Uint8Array([...new Uint8Array(length - msg.length), ...msg])
+  }
+  return msg
```
Comment (jochem-brouwer) [inline packages/util/src/bytes.ts:152]: I had to check here if the original returned a copy, but `subarray` returns a view of the array so this is not the case (so this is fine 😄 👍 )

File: packages/util/test/bytes.spec.ts [hunk 2]
```diff
@@ -372,6 +384,26 @@ describe('bytesToBigInt', () => {
...
+    assert.throws(function () {
+      // @ts-expect-error -- Testing invalid input
+      bytesToBigInt([1, 2, 3])
+    }, /This method only supports Uint8Array/)
+  })
+  it('should not mutate input when littleEndian is true', () => {
+    const bytes = new Uint8Array([0x01, 0x02, 0x03])
+    const original = new Uint8Array([0x01, 0x02, 0x03])
+    bytesToBigInt(bytes, true)
+    assert.deepEqual(bytes, original)
```
Comment (jochem-brouwer) [inline packages/util/test/bytes.spec.ts:400]: What does this test? I'm not sure why this would mutate, is this because of the little endianness? So we would "mirror" the array so we can convert it and we thus check that it does not alter the original?

**Review by jochem-brouwer — COMMENTED** [review]
This looks good to me, but I am slightly surprised that only the `ecrecover` precompile needed an edit for too small inputs to be allowed here. I would expect more EVM errors.
I have to go over EVM once again to see if there are no edge cases where an error might occur where this did not happen in the past.
I also think this is somewhat breaking-ish since we now throw when we try to truncate when it is not explicitly allowed?

File: packages/util/test/bytes.spec.ts (hunk 2 above)
Comment (gabrocheleau) [reply packages/util/test/bytes.spec.ts:400]: That test is just guarding against accidental mutation. In the little‑endian path we reverse a copy, not the original buffer, so bytesToBigInt(bytes, true) must leave the caller’s Uint8Array unchanged. The test feeds [0x01, 0x02, 0x03], calls with littleEndian=true, and then asserts the original array is still [0x01, 0x02, 0x03]. It’s not about endianness semantics per se, just ensuring we don’t mutate the caller’s input when we “mirror” it for the LE conversion.

Comment (jochem-brouwer) [reply packages/util/test/bytes.spec.ts:400]: Ah right makes sense :smile: :+1:

**Review by jochem-brouwer — APPROVED** [review]
LGTM!

Release-wise we might want to check how "breaking" this is regarding versioning the release 😄 👍
